<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/06/29 10:01:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=demo.payroll.com;port=3306;dbname=payroll',
  'username' => 'root',
  'password' => 'root',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
