<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/06/29 10:02:08
sfConfig::add(array(
  'mod_securityauthentication_enabled' => true,
  'mod_securityauthentication_view_class' => 'sfPHP',
));
