<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/06/29 10:02:08
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
  ),
  'securityauthenticationconfigure' => 
  array (
    'is_secure' => true,
  ),
);
